improve(slb): improve this module and add examples
terraform-alicloud-modules/terraform-alicloud-slb-listener pull request #2
Opened 2020-02-24 09:03 UTC by Lexsss

2020-02-24 10:17 UTC, xiaozhu36 requested changes

2020-02-24 10:17 UTC, xiaozhu36 commented on main.tf
> +          scheduler       = lookup(obj, "scheduler", "wrr")
listener 中也应该支持获取health check，advance setting 一起其他参数中的参数，当这些参数在listener中没有指定的时候，再从health check，advance setting等中取
也就是说listener中应该支持所有的参数，但是health check中只支持health相关的，listerner中的health check只用于某个单独的listener，而health check中的health适用于所有listenre

2020-02-24 10:17 UTC, xiaozhu36 commented on main.tf
> +          scheduler       = lookup(obj, "scheduler", "wrr")
其他参数也一样

2020-02-24 11:53 UTC, zql-tqy commented on README-CN.md
> +本模板要求使用版本 Terraform 0.12.
没有加provider的版本

2020-02-24 11:53 UTC, zql-tqy commented on README-CN.md
> +* 本 Module 使用的 AccessKey 和 SecretKey 可以直接从 `profile` 和 `shared_credentials_file` 中获取。如果未设置，可通过下载安装 [aliyun-cli](https://github.com/aliyun/aliyun-cli#installation) 后进行配置.
这个使用中文的标点吧

2020-02-24 11:53 UTC, zql-tqy commented on variables.tf
> +  default     = ""
这几个变量没有type

2020-02-24 11:53 UTC, zql-tqy commented on variables.tf
> +  description = "(Deprecated) Threshold determining the result of the health check is success."
这个需要写上从哪个版本开始替换，用哪个参数替换吧

2020-02-24 14:04 UTC, zql-tqy commented on examples/basic-example/main.tf
> +
添加上profile的参数吧

2020-02-24 15:22 UTC, xiaozhu36 requested changes

2020-02-24 15:22 UTC, xiaozhu36 commented on README-CN.md
> +  profile = "Your-Profile-Name"
region

2020-02-24 15:22 UTC, xiaozhu36 commented on README-CN.md
> +    // TCP
advance_setting 中为啥还有health check的字段

2020-02-24 15:22 UTC, xiaozhu36 commented on main.tf
> +          sticky_session            = lookup(obj, "sticky_session", null)
后面的null可以直接改成从health check，advance setting和x_forwarded_for中取，这样在后面具体写resource的时候就不用了

2020-02-24 15:22 UTC, xiaozhu36 commented on main.tf
>    x_forwarded_for {
x_forwarded_for 从advance setting中拿出来吧，跟 advance setting 评级，这样看的清楚些
另外，再加一个参数 ssl_certificates ，也跟 advance setting，是一个map，存放证书相关的参数, 用于https listener的设置

2020-02-24 15:22 UTC, xiaozhu36 commented on variables.tf
> +  description = "The slb listener health check settings. It supports fields 'healthy_threshold','unhealthy_threshold','health_check_timeout' and 'health_check_interval'"
应该不止这四个参数吧，健康检查相关的都要加进来

2020-02-24 15:22 UTC, xiaozhu36 commented on examples/basic-example/main.tf
> +  profile = var.profile
region

2020-02-24 15:22 UTC, xiaozhu36 commented on variables.tf
> +  description = "The slb listener advance settings."
advance setting中支持哪些参数，也列一下吧，多也没关系

2020-02-25 01:06 UTC, xiaozhu36 requested changes

2020-02-25 01:06 UTC, xiaozhu36 commented on main.tf
> +          enable_http2              = lookup(obj, "enable_http2", lookup(var.advance_setting, "enable_http2", null))
enable_http2 应该属于 ssl_certificates 中的参数

2020-02-25 01:06 UTC, xiaozhu36 commented on outputs.tf
> +  this_slb_id = length(local.listeners) == 0 ? var.slb : concat(alicloud_slb_listener.this.*.load_balancer_id, [""])[0]
这个直接就是 this_slb_id = var.slb

2020-02-25 01:06 UTC, xiaozhu36 commented on variables.tf
> +  description = "The slb listener health check settings. It's supports fields 'healthy_threshold','unhealthy_threshold','health_check_timeout', 'health_check', 'health_check_type', 'health_check_conn
description = "The slb listener health check settings to use on listeners. It's supports fields 'healthy_threshold','unhealthy_threshold','health_check_timeout', 'health_check', 'health_check_type', 'health_check_connect_port', 'health_check_domain', 'health_check_uri', 'health_check_http_code', 'health_check_method' and 'health_check_interval'"

2020-02-25 01:06 UTC, xiaozhu36 commented on variables.tf
> +  description = "The slb listener advance settings, It's supports fields 'sticky_session', 'sticky_session_type', 'cookie', 'cookie_timeout', 'gzip', 'persistence_timeout', 'acl_status', 'acl_type',
description = "The slb listener advance settings to use on listeners. It's supports fields 'sticky_session', 'sticky_session_type', 'cookie', 'cookie_timeout', 'gzip', 'persistence_timeout', 'acl_status', 'acl_type', 'acl_id', 'idle_timeout' and 'request_timeout'."

2020-02-25 01:06 UTC, xiaozhu36 commented on variables.tf
> +  description = "Whether to set additional HTTP Header field 'X-Forwarded-For' (documented below), It's supports fields 'retrive_slb_ip', 'retrive_slb_id' and 'retrive_slb_proto'"
description = "Additional HTTP Header field 'X-Forwarded-For'  to use on listeners. It's supports fields 'retrive_slb_ip', 'retrive_slb_id' and 'retrive_slb_proto'"

2020-02-25 01:06 UTC, xiaozhu36 commented on variables.tf
> +  description = "SLB Server certificate settings, It's supports fields 'tls_cipher_policy' and 'server_certificate_id'"
description = "SLB Server certificate settings to use on listeners. It's supports fields 'tls_cipher_policy', 'server_certificate_id' and 'enable_http2'"

2020-02-25 01:06 UTC, xiaozhu36 commented on variables.tf
>    description = "The load balancer ID used to add a new listener."
description = "The load balancer ID used to add one or more listeners."

2020-02-25 01:06 UTC, xiaozhu36 commented on variables.tf
> +  description = "The list of slb listeners, It's supports all fields of alicloud_slb_listener resource."
description = "List of slb listeners. Each item can set all or part fields of alicloud_slb_listener resource."

2020-02-25 01:06 UTC, xiaozhu36 commented on README.md
> +  // you can also leave this field unspecified to use the default value
// health_check will apply to all of listeners if health checking is not set in the listeners

2020-02-25 01:06 UTC, xiaozhu36 commented on README.md
> +  // you can also leave this field unspecified to use the default value
advance_setting 改为 advanced_setting
advanced_setting will apply to all of listeners if some fields are not set in the listeners

2020-02-25 01:06 UTC, xiaozhu36 commented on README.md
> +  // you can also leave this field unspecified to use the default value
x_forwarded_for will apply to all of listeners if it is not set in the listeners

2020-02-25 01:06 UTC, xiaozhu36 commented on README.md
> +  // you can also leave this field unspecified to use the default value
// ssl_certificates will apply to all of https listeners if it is not set in the listeners

2020-02-25 02:32 UTC, xiaozhu36 approved these changes

2020-02-25 02:32 UTC, merged